server:
  port: 8080

spring:
  datasource:
    # 这里的 localhost 就是你本机
    url: jdbc:mysql://localhost:3306/airbook?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456  # <--- 记得改成你的！
    driver-class-name: com.mysql.cj.jdbc.Driver

# 简单的 MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
